services:
  trdemo.haiut.dev.spyd.io:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://trdemo.haiut.dev.spyd.io'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: trdemo
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
version: '3.3'
