services:
  auth.stg.testr.io:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://auth.stg.testr.io'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: auth
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  stg.testr.io:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://stg.testr.io'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: stg
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  www.il.kayak.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://www.il.kayak.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: www
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  www.kayak.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://www.kayak.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: www
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
version: '3.3'
