services:
  api.goavail.io:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://api.goavail.io'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: api
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  api.permutive.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://api.permutive.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: api
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  availcarsharing.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://availcarsharing.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: availcarsharing
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  backend.upapi.net:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://backend.upapi.net'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: backend
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  bh.contextweb.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://bh.contextweb.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: bh
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  cds.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://cds.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: cds
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  drivedrift.zendesk.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://drivedrift.zendesk.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: drivedrift
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  events.browsiprod.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://events.browsiprod.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: events
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  la-sync.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://la-sync.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: la-sync
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  match.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://match.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: match
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  match.zorosrv.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://match.zorosrv.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: match
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  nr-events.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://nr-events.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: nr-events
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  pixel.onaudience.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://pixel.onaudience.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: pixel
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  profile.goavail.io:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://profile.goavail.io'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: profile
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  rtb.mfadsrvr.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://rtb.mfadsrvr.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: rtb
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  sb.scorecardresearch.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://sb.scorecardresearch.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: sb
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  server.exposebox.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://server.exposebox.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: server
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  trc-events.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://trc-events.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: trc-events
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  trc.taboola.com:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://trc.taboola.com'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: trc
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  up9.atlassian.net:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://up9.atlassian.net'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: up9
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  www.ynet.co.il:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://www.ynet.co.il'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: www
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
  z.ynet.co.il:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'https://z.ynet.co.il'
    environment:
    - MOCKINTOSH_FORCE_PORT=443
    hostname: z
    image: testrio/mockintosh:latest
    ports:
    - 443
    read_only: true
    volumes:
    - .:/config
version: '3.3'
